using Microsoft.EntityFrameworkCore;

namespace DriveTraceCore.Api.Data;

public static class SchemaEvolution
{
    public static async Task EnsurePhase34Async(DriveTraceDbContext db, CancellationToken cancellationToken = default)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Customers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "CustomerCode" character varying(80) NOT NULL,
                "Name" character varying(160) NOT NULL,
                "ContactEmail" character varying(180) NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "SimulationRuns" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "RunCode" character varying(80) NOT NULL,
                "Name" character varying(160) NOT NULL,
                "ScenarioKey" character varying(80) NOT NULL,
                "Status" character varying(40) NOT NULL DEFAULT 'Draft',
                "ExecutionMode" character varying(20) NOT NULL DEFAULT 'Manual',
                "StartedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "PausedAt" timestamp with time zone NULL,
                "CompletedAt" timestamp with time zone NULL,
                "CurrentStep" integer NOT NULL DEFAULT 0,
                "CreatedByUserId" character varying(120) NULL,
                "Notes" text NULL,
                CONSTRAINT "PK_SimulationRuns" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "SimulationSteps" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "SimulationRunId" integer NOT NULL,
                "StepNumber" integer NOT NULL,
                "StepType" character varying(80) NOT NULL,
                "Description" character varying(180) NOT NULL,
                "ExecutedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "ProductUnitId" integer NULL,
                "ManufacturingOrderId" integer NULL,
                "FromLineId" integer NULL,
                "ToLineId" integer NULL,
                "FromSectionId" integer NULL,
                "ToSectionId" integer NULL,
                "Result" character varying(40) NULL,
                "OperationalEventId" integer NULL,
                CONSTRAINT "PK_SimulationSteps" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_SimulationSteps_SimulationRuns_SimulationRunId" FOREIGN KEY ("SimulationRunId") REFERENCES "SimulationRuns" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_SimulationSteps_ProductUnits_ProductUnitId" FOREIGN KEY ("ProductUnitId") REFERENCES "ProductUnits" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ManufacturingOrders_ManufacturingOrderId" FOREIGN KEY ("ManufacturingOrderId") REFERENCES "ManufacturingOrders" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ProductionLines_FromLineId" FOREIGN KEY ("FromLineId") REFERENCES "ProductionLines" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ProductionLines_ToLineId" FOREIGN KEY ("ToLineId") REFERENCES "ProductionLines" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ProductionLineSections_FromSectionId" FOREIGN KEY ("FromSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ProductionLineSections_ToSectionId" FOREIGN KEY ("ToSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_OperationalEvents_OperationalEventId" FOREIGN KEY ("OperationalEventId") REFERENCES "OperationalEvents" ("Id") ON DELETE SET NULL
            );

            CREATE TABLE IF NOT EXISTS "ProductUnitLocationHistory" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProductUnitId" integer NOT NULL,
                "FromProductionLineId" integer NULL,
                "ToProductionLineId" integer NULL,
                "FromSectionId" integer NULL,
                "ToSectionId" integer NOT NULL,
                "FromSupportId" integer NULL,
                "ToSupportId" integer NULL,
                "EventType" character varying(80) NOT NULL DEFAULT 'Transfer',
                "Reason" character varying(160) NOT NULL DEFAULT 'Operational movement',
                "Notes" text NULL,
                "OperatorUserId" character varying(120) NULL,
                "OccurredAt" timestamp with time zone NOT NULL DEFAULT now(),
                "Source" character varying(80) NOT NULL DEFAULT 'api',
                "CorrelationId" character varying(80) NULL,
                CONSTRAINT "PK_ProductUnitLocationHistory" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductUnits_ProductUnitId" FOREIGN KEY ("ProductUnitId") REFERENCES "ProductUnits" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductionLines_FromProductionLineId" FOREIGN KEY ("FromProductionLineId") REFERENCES "ProductionLines" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductionLines_ToProductionLineId" FOREIGN KEY ("ToProductionLineId") REFERENCES "ProductionLines" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductionLineSections_FromSectionId" FOREIGN KEY ("FromSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductionLineSections_ToSectionId" FOREIGN KEY ("ToSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_Supports_FromSupportId" FOREIGN KEY ("FromSupportId") REFERENCES "Supports" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_Supports_ToSupportId" FOREIGN KEY ("ToSupportId") REFERENCES "Supports" ("Id") ON DELETE RESTRICT
            );

            CREATE TABLE IF NOT EXISTS "OperationalEvents" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "EventCode" character varying(80) NOT NULL,
                "EventType" character varying(80) NOT NULL,
                "ProductUnitId" integer NULL,
                "SupportId" integer NULL,
                "ManufacturingOrderId" integer NULL,
                "FromProductionLineId" integer NULL,
                "ToProductionLineId" integer NULL,
                "FromSectionId" integer NULL,
                "ToSectionId" integer NULL,
                "CheckpointId" integer NULL,
                "QualityResultId" integer NULL,
                "NonconformityId" integer NULL,
                "ReworkRecordId" integer NULL,
                "ScrapRecordId" integer NULL,
                "RackId" integer NULL,
                "ReasonCode" character varying(80) NULL,
                "Severity" character varying(40) NULL,
                "Source" character varying(40) NOT NULL DEFAULT 'Api',
                "PerformedByUserId" character varying(120) NULL,
                "OccurredAt" timestamp with time zone NOT NULL DEFAULT now(),
                "Notes" text NULL,
                "IsDemo" boolean NOT NULL DEFAULT FALSE,
                "MetadataJson" text NULL,
                CONSTRAINT "PK_OperationalEvents" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_OperationalEvents_ProductUnits_ProductUnitId" FOREIGN KEY ("ProductUnitId") REFERENCES "ProductUnits" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_Supports_SupportId" FOREIGN KEY ("SupportId") REFERENCES "Supports" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ManufacturingOrders_ManufacturingOrderId" FOREIGN KEY ("ManufacturingOrderId") REFERENCES "ManufacturingOrders" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ProductionLines_FromProductionLineId" FOREIGN KEY ("FromProductionLineId") REFERENCES "ProductionLines" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ProductionLines_ToProductionLineId" FOREIGN KEY ("ToProductionLineId") REFERENCES "ProductionLines" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ProductionLineSections_FromSectionId" FOREIGN KEY ("FromSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ProductionLineSections_ToSectionId" FOREIGN KEY ("ToSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_Checkpoints_CheckpointId" FOREIGN KEY ("CheckpointId") REFERENCES "Checkpoints" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_QualityResults_QualityResultId" FOREIGN KEY ("QualityResultId") REFERENCES "QualityResults" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_Nonconformities_NonconformityId" FOREIGN KEY ("NonconformityId") REFERENCES "Nonconformities" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ReworkRecords_ReworkRecordId" FOREIGN KEY ("ReworkRecordId") REFERENCES "ReworkRecords" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ScrapRecords_ScrapRecordId" FOREIGN KEY ("ScrapRecordId") REFERENCES "ScrapRecords" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_Racks_RackId" FOREIGN KEY ("RackId") REFERENCES "Racks" ("Id") ON DELETE SET NULL
            );

            CREATE TABLE IF NOT EXISTS "ReconditionRecords" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProductUnitId" integer NOT NULL,
                "NonconformityId" integer NULL,
                "ReworkRecordId" integer NULL,
                "Status" character varying(40) NOT NULL DEFAULT 'Candidate',
                "Decision" character varying(40) NOT NULL DEFAULT 'Pending',
                "Reason" text NULL,
                "Notes" text NULL,
                "FunctionalValidation" boolean NOT NULL DEFAULT FALSE,
                "RecordedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "CompletedAt" timestamp with time zone NULL,
                "RejectedAt" timestamp with time zone NULL,
                "RecordedByResourceId" integer NULL,
                "PerformedByUserId" character varying(120) NULL,
                "NextDisposition" character varying(40) NULL,
                CONSTRAINT "PK_ReconditionRecords" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ReconditionRecords_ProductUnits_ProductUnitId" FOREIGN KEY ("ProductUnitId") REFERENCES "ProductUnits" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_ReconditionRecords_Nonconformities_NonconformityId" FOREIGN KEY ("NonconformityId") REFERENCES "Nonconformities" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_ReconditionRecords_ReworkRecords_ReworkRecordId" FOREIGN KEY ("ReworkRecordId") REFERENCES "ReworkRecords" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_ReconditionRecords_Resources_RecordedByResourceId" FOREIGN KEY ("RecordedByResourceId") REFERENCES "Resources" ("Id") ON DELETE SET NULL
            );

            CREATE TABLE IF NOT EXISTS "SimulationRuns" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "RunCode" character varying(80) NOT NULL,
                "Name" character varying(160) NOT NULL,
                "ScenarioKey" character varying(80) NOT NULL,
                "Status" character varying(40) NOT NULL DEFAULT 'Draft',
                "ExecutionMode" character varying(20) NOT NULL DEFAULT 'Manual',
                "StartedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "PausedAt" timestamp with time zone NULL,
                "CompletedAt" timestamp with time zone NULL,
                "CurrentStep" integer NOT NULL DEFAULT 0,
                "CreatedByUserId" character varying(120) NULL,
                "Notes" text NULL,
                CONSTRAINT "PK_SimulationRuns" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "SimulationSteps" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "SimulationRunId" integer NOT NULL,
                "StepNumber" integer NOT NULL,
                "StepType" character varying(80) NOT NULL,
                "Description" character varying(180) NOT NULL,
                "ExecutedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "ProductUnitId" integer NULL,
                "ManufacturingOrderId" integer NULL,
                "FromLineId" integer NULL,
                "ToLineId" integer NULL,
                "FromSectionId" integer NULL,
                "ToSectionId" integer NULL,
                "Result" character varying(40) NULL,
                "OperationalEventId" integer NULL,
                CONSTRAINT "PK_SimulationSteps" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_SimulationSteps_SimulationRuns_SimulationRunId" FOREIGN KEY ("SimulationRunId") REFERENCES "SimulationRuns" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_SimulationSteps_ProductUnits_ProductUnitId" FOREIGN KEY ("ProductUnitId") REFERENCES "ProductUnits" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ManufacturingOrders_ManufacturingOrderId" FOREIGN KEY ("ManufacturingOrderId") REFERENCES "ManufacturingOrders" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ProductionLines_FromLineId" FOREIGN KEY ("FromLineId") REFERENCES "ProductionLines" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ProductionLines_ToLineId" FOREIGN KEY ("ToLineId") REFERENCES "ProductionLines" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ProductionLineSections_FromSectionId" FOREIGN KEY ("FromSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_ProductionLineSections_ToSectionId" FOREIGN KEY ("ToSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_SimulationSteps_OperationalEvents_OperationalEventId" FOREIGN KEY ("OperationalEventId") REFERENCES "OperationalEvents" ("Id") ON DELETE SET NULL
            );

            ALTER TABLE "ProductionLines" ADD COLUMN IF NOT EXISTS "DisplayOrder" integer NOT NULL DEFAULT 0;
            ALTER TABLE "ProductionLines" ADD COLUMN IF NOT EXISTS "VisualGroup" character varying(80) NULL;

            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "DisplayOrder" integer NOT NULL DEFAULT 0;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "LayoutColumn" integer NULL;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "LayoutRow" integer NULL;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "VisualZone" character varying(80) NULL;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "IsTransferPoint" boolean NOT NULL DEFAULT FALSE;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "AllowsLineTransferIn" boolean NOT NULL DEFAULT FALSE;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "AllowsLineTransferOut" boolean NOT NULL DEFAULT FALSE;

            ALTER TABLE "ManufacturingOrders" ADD COLUMN IF NOT EXISTS "CustomerId" integer NULL;
            ALTER TABLE "ManufacturingOrders" ADD COLUMN IF NOT EXISTS "CustomerReference" character varying(120) NULL;
            ALTER TABLE "ManufacturingOrders" ADD COLUMN IF NOT EXISTS "PublicTrackingCode" character varying(80) NULL;

            ALTER TABLE "ProductUnits" ADD COLUMN IF NOT EXISTS "IsReconditioned" boolean NOT NULL DEFAULT FALSE;
            ALTER TABLE "ProductUnits" ADD COLUMN IF NOT EXISTS "ReconditionedAt" timestamp with time zone NULL;
            ALTER TABLE "ProductUnits" ADD COLUMN IF NOT EXISTS "ReconditionReason" text NULL;
            ALTER TABLE "ProductUnits" ADD COLUMN IF NOT EXISTS "ReconditionedFromNonconformityId" integer NULL;
            ALTER TABLE "ProductUnits" ADD COLUMN IF NOT EXISTS "ReconditionedByResourceId" integer NULL;
            ALTER TABLE "ProductUnits" ADD COLUMN IF NOT EXISTS "RecoveryStatus" character varying(40) NULL DEFAULT 'None';
            ALTER TABLE "ProductUnits" ADD COLUMN IF NOT EXISTS "QualityDisposition" character varying(40) NULL;

            ALTER TABLE "OperationalEvents" ADD COLUMN IF NOT EXISTS "ReconditionRecordId" integer NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Customers_CustomerCode" ON "Customers" ("CustomerCode");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ManufacturingOrders_PublicTrackingCode" ON "ManufacturingOrders" ("PublicTrackingCode") WHERE "PublicTrackingCode" IS NOT NULL;
            CREATE INDEX IF NOT EXISTS "IX_ManufacturingOrders_CustomerId" ON "ManufacturingOrders" ("CustomerId");
            CREATE INDEX IF NOT EXISTS "IX_ProductUnits_ReconditionedFromNonconformityId" ON "ProductUnits" ("ReconditionedFromNonconformityId");
            CREATE INDEX IF NOT EXISTS "IX_ProductUnits_ReconditionedByResourceId" ON "ProductUnits" ("ReconditionedByResourceId");
            CREATE INDEX IF NOT EXISTS "IX_ProductUnitLocationHistory_ProductUnitId_OccurredAt" ON "ProductUnitLocationHistory" ("ProductUnitId", "OccurredAt");
            CREATE INDEX IF NOT EXISTS "IX_ProductUnitLocationHistory_ToProductionLineId_OccurredAt" ON "ProductUnitLocationHistory" ("ToProductionLineId", "OccurredAt");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_OperationalEvents_EventCode" ON "OperationalEvents" ("EventCode");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_OccurredAt_EventType" ON "OperationalEvents" ("OccurredAt", "EventType");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_ProductUnitId_OccurredAt" ON "OperationalEvents" ("ProductUnitId", "OccurredAt");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_SupportId_OccurredAt" ON "OperationalEvents" ("SupportId", "OccurredAt");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_ManufacturingOrderId_OccurredAt" ON "OperationalEvents" ("ManufacturingOrderId", "OccurredAt");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_ReconditionRecordId" ON "OperationalEvents" ("ReconditionRecordId");
            CREATE INDEX IF NOT EXISTS "IX_ReconditionRecords_ProductUnitId_Status" ON "ReconditionRecords" ("ProductUnitId", "Status");
            CREATE INDEX IF NOT EXISTS "IX_ReconditionRecords_NonconformityId" ON "ReconditionRecords" ("NonconformityId");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SimulationRuns_RunCode" ON "SimulationRuns" ("RunCode");
            CREATE INDEX IF NOT EXISTS "IX_SimulationRuns_ScenarioKey_Status_StartedAt" ON "SimulationRuns" ("ScenarioKey", "Status", "StartedAt");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SimulationSteps_SimulationRunId_StepNumber" ON "SimulationSteps" ("SimulationRunId", "StepNumber");
            CREATE INDEX IF NOT EXISTS "IX_SimulationSteps_SimulationRunId_ExecutedAt" ON "SimulationSteps" ("SimulationRunId", "ExecutedAt");

            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ProductUnits_Nonconformities_ReconditionedFromNonconformityId') THEN
                    ALTER TABLE "ProductUnits" ADD CONSTRAINT "FK_ProductUnits_Nonconformities_ReconditionedFromNonconformityId" FOREIGN KEY ("ReconditionedFromNonconformityId") REFERENCES "Nonconformities" ("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ProductUnits_Resources_ReconditionedByResourceId') THEN
                    ALTER TABLE "ProductUnits" ADD CONSTRAINT "FK_ProductUnits_Resources_ReconditionedByResourceId" FOREIGN KEY ("ReconditionedByResourceId") REFERENCES "Resources" ("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OperationalEvents_ReconditionRecords_ReconditionRecordId') THEN
                    ALTER TABLE "OperationalEvents" ADD CONSTRAINT "FK_OperationalEvents_ReconditionRecords_ReconditionRecordId" FOREIGN KEY ("ReconditionRecordId") REFERENCES "ReconditionRecords" ("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_SimulationSteps_OperationalEvents_OperationalEventId') THEN
                    ALTER TABLE "SimulationSteps" ADD CONSTRAINT "FK_SimulationSteps_OperationalEvents_OperationalEventId" FOREIGN KEY ("OperationalEventId") REFERENCES "OperationalEvents" ("Id") ON DELETE SET NULL;
                END IF;
            END $$;
            """, cancellationToken);
    }
}
