using Microsoft.EntityFrameworkCore;

namespace DriveTraceCore.Api.Data;

public static class SchemaEvolution
{
    public static async Task EnsurePhase34Async(DriveTraceDbContext db, CancellationToken cancellationToken = default)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Customers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "CustomerCode" character varying(80) NOT NULL,
                "Name" character varying(160) NOT NULL,
                "ContactEmail" character varying(180) NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "ProductUnitLocationHistory" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ProductUnitId" integer NOT NULL,
                "FromProductionLineId" integer NULL,
                "ToProductionLineId" integer NULL,
                "FromSectionId" integer NULL,
                "ToSectionId" integer NOT NULL,
                "FromSupportId" integer NULL,
                "ToSupportId" integer NULL,
                "EventType" character varying(80) NOT NULL DEFAULT 'Transfer',
                "Reason" character varying(160) NOT NULL DEFAULT 'Operational movement',
                "Notes" text NULL,
                "OperatorUserId" character varying(120) NULL,
                "OccurredAt" timestamp with time zone NOT NULL DEFAULT now(),
                "Source" character varying(80) NOT NULL DEFAULT 'api',
                "CorrelationId" character varying(80) NULL,
                CONSTRAINT "PK_ProductUnitLocationHistory" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductUnits_ProductUnitId" FOREIGN KEY ("ProductUnitId") REFERENCES "ProductUnits" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductionLines_FromProductionLineId" FOREIGN KEY ("FromProductionLineId") REFERENCES "ProductionLines" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductionLines_ToProductionLineId" FOREIGN KEY ("ToProductionLineId") REFERENCES "ProductionLines" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductionLineSections_FromSectionId" FOREIGN KEY ("FromSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_ProductionLineSections_ToSectionId" FOREIGN KEY ("ToSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_Supports_FromSupportId" FOREIGN KEY ("FromSupportId") REFERENCES "Supports" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ProductUnitLocationHistory_Supports_ToSupportId" FOREIGN KEY ("ToSupportId") REFERENCES "Supports" ("Id") ON DELETE RESTRICT
            );

            CREATE TABLE IF NOT EXISTS "OperationalEvents" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "EventCode" character varying(80) NOT NULL,
                "EventType" character varying(80) NOT NULL,
                "ProductUnitId" integer NULL,
                "SupportId" integer NULL,
                "ManufacturingOrderId" integer NULL,
                "FromProductionLineId" integer NULL,
                "ToProductionLineId" integer NULL,
                "FromSectionId" integer NULL,
                "ToSectionId" integer NULL,
                "CheckpointId" integer NULL,
                "QualityResultId" integer NULL,
                "NonconformityId" integer NULL,
                "ReworkRecordId" integer NULL,
                "ScrapRecordId" integer NULL,
                "RackId" integer NULL,
                "ReasonCode" character varying(80) NULL,
                "Severity" character varying(40) NULL,
                "Source" character varying(40) NOT NULL DEFAULT 'Api',
                "PerformedByUserId" character varying(120) NULL,
                "OccurredAt" timestamp with time zone NOT NULL DEFAULT now(),
                "Notes" text NULL,
                "IsDemo" boolean NOT NULL DEFAULT FALSE,
                "MetadataJson" text NULL,
                CONSTRAINT "PK_OperationalEvents" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_OperationalEvents_ProductUnits_ProductUnitId" FOREIGN KEY ("ProductUnitId") REFERENCES "ProductUnits" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_Supports_SupportId" FOREIGN KEY ("SupportId") REFERENCES "Supports" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ManufacturingOrders_ManufacturingOrderId" FOREIGN KEY ("ManufacturingOrderId") REFERENCES "ManufacturingOrders" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ProductionLines_FromProductionLineId" FOREIGN KEY ("FromProductionLineId") REFERENCES "ProductionLines" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ProductionLines_ToProductionLineId" FOREIGN KEY ("ToProductionLineId") REFERENCES "ProductionLines" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ProductionLineSections_FromSectionId" FOREIGN KEY ("FromSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ProductionLineSections_ToSectionId" FOREIGN KEY ("ToSectionId") REFERENCES "ProductionLineSections" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_Checkpoints_CheckpointId" FOREIGN KEY ("CheckpointId") REFERENCES "Checkpoints" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_QualityResults_QualityResultId" FOREIGN KEY ("QualityResultId") REFERENCES "QualityResults" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_Nonconformities_NonconformityId" FOREIGN KEY ("NonconformityId") REFERENCES "Nonconformities" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ReworkRecords_ReworkRecordId" FOREIGN KEY ("ReworkRecordId") REFERENCES "ReworkRecords" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_ScrapRecords_ScrapRecordId" FOREIGN KEY ("ScrapRecordId") REFERENCES "ScrapRecords" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_OperationalEvents_Racks_RackId" FOREIGN KEY ("RackId") REFERENCES "Racks" ("Id") ON DELETE SET NULL
            );

            ALTER TABLE "ProductionLines" ADD COLUMN IF NOT EXISTS "DisplayOrder" integer NOT NULL DEFAULT 0;
            ALTER TABLE "ProductionLines" ADD COLUMN IF NOT EXISTS "VisualGroup" character varying(80) NULL;

            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "DisplayOrder" integer NOT NULL DEFAULT 0;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "LayoutColumn" integer NULL;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "LayoutRow" integer NULL;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "VisualZone" character varying(80) NULL;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "IsTransferPoint" boolean NOT NULL DEFAULT FALSE;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "AllowsLineTransferIn" boolean NOT NULL DEFAULT FALSE;
            ALTER TABLE "ProductionLineSections" ADD COLUMN IF NOT EXISTS "AllowsLineTransferOut" boolean NOT NULL DEFAULT FALSE;

            ALTER TABLE "ManufacturingOrders" ADD COLUMN IF NOT EXISTS "CustomerId" integer NULL;
            ALTER TABLE "ManufacturingOrders" ADD COLUMN IF NOT EXISTS "CustomerReference" character varying(120) NULL;
            ALTER TABLE "ManufacturingOrders" ADD COLUMN IF NOT EXISTS "PublicTrackingCode" character varying(80) NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Customers_CustomerCode" ON "Customers" ("CustomerCode");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ManufacturingOrders_PublicTrackingCode" ON "ManufacturingOrders" ("PublicTrackingCode") WHERE "PublicTrackingCode" IS NOT NULL;
            CREATE INDEX IF NOT EXISTS "IX_ManufacturingOrders_CustomerId" ON "ManufacturingOrders" ("CustomerId");
            CREATE INDEX IF NOT EXISTS "IX_ProductUnitLocationHistory_ProductUnitId_OccurredAt" ON "ProductUnitLocationHistory" ("ProductUnitId", "OccurredAt");
            CREATE INDEX IF NOT EXISTS "IX_ProductUnitLocationHistory_ToProductionLineId_OccurredAt" ON "ProductUnitLocationHistory" ("ToProductionLineId", "OccurredAt");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_OperationalEvents_EventCode" ON "OperationalEvents" ("EventCode");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_OccurredAt_EventType" ON "OperationalEvents" ("OccurredAt", "EventType");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_ProductUnitId_OccurredAt" ON "OperationalEvents" ("ProductUnitId", "OccurredAt");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_SupportId_OccurredAt" ON "OperationalEvents" ("SupportId", "OccurredAt");
            CREATE INDEX IF NOT EXISTS "IX_OperationalEvents_ManufacturingOrderId_OccurredAt" ON "OperationalEvents" ("ManufacturingOrderId", "OccurredAt");
            """, cancellationToken);
    }
}
